source "https://rubygems.org"

gem 'jekyll'
gem 'jekyll-feed'
gem 'jekyll-seo-tag'
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'jekyll-toc'
gem 'jekyll-reading-time'
gem 'jekyll-time-to-read'
gem 'jekyll_google_translate'
gem 'eventmachine'
gem 'jekyll-google_search_console_verification_file'
gem 'bigdecimal', '3.1.9'
gem 'google-protobuf', '4.29.2'
gem 'sass-embedded', '1.83.0'
gem 'rexml', '3.4.0'